# Generated by Django 5.0.6 on 2024-07-22 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="experiences",
            new_name="experience",
        ),
    ]
