# Generated by Django 5.0.6 on 2024-08-06 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0002_alter_wishlist_experienes_alter_wishlist_rooms_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="experienes",
            new_name="experiences",
        ),
    ]
